# Generated by Django 6.0.6 on 2026-07-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tornado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ef_rating', models.CharField(choices=[('EF0', 'EF0'), ('EF1', 'EF1'), ('EF2', 'EF2'), ('EF3', 'EF3'), ('EF4', 'EF4'), ('EF5', 'EF5')], max_length=3)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('plot_image', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
